/*
4. You are given two strings s and t.
‌
String t is generated by random shuffling string s and then add one more letter at a random position.
‌
Return the letter that was added to t.
‌
Example 1:
Input: s = "abcd", t = "abcde"
Output: "e"
Explanation: 'e' is the letter that was added.
‌
Example 2:
Input: s = "", t = "y"
Output: "y"
‌
Constraints:
0 <= s.length <= 1000
t.length == s.length + 1
s and t consist of lowercase English letters.*/

import java.util.Scanner;
class FindAddedLetter
{
	public static void main(String[] args)
	{
		Scanner sc = new Scanner(System.in);
		System.out.println("Enter String 1: ");
		String str1 = sc.nextLine();
		System.out.println("Enter String 2: ");
		String str2 = sc.nextLine();
		char result = findLetter(str1, str2);
		System.out.println(result);
	}
	public static char findLetter(String str1, String str2)
	{
		int len1 = str1.length();
		int len2 = str2.length();

		char ch = 'a';
		
		for(int i = 0; i<str1.length();i++)
		{
			for(int j =0; j<str2.length(); j++)
			{
				if(str1.charAt(i) == str2.charAt(j))
				{
					continue;
				}
				else
				{
					ch = str2.charAt(j);
				}
			}
		}
		return ch;
		
	}
}